# Target = ResourceGroup
# Generated by OwnerLens. Review before running.
# Requires the Az PowerShell module and an authenticated Azure session.
param(
  [string]$TagName = {{ tagName }}
)

$targets = @(
{{ targets }}
)

foreach ($target in $targets) {
  if ([string]::IsNullOrWhiteSpace($target.Owner)) {
    Write-Warning "Skipping $($target.SubscriptionId)/$($target.ResourceGroupName): no resolved owner."
    continue
  }

  Set-AzContext -SubscriptionId $target.SubscriptionId | Out-Null
  $group = Get-AzResourceGroup -Name $target.ResourceGroupName -ErrorAction Stop
  $tags = @{}
  if ($group.Tags) {
    foreach ($key in $group.Tags.Keys) {
      $tags[$key] = $group.Tags[$key]
    }
  }
  $tags[$TagName] = $target.Owner
  Set-AzResourceGroup -Name $target.ResourceGroupName -Tag $tags -ErrorAction Stop
}
