# Target = ServicePrincipal
# Generated by OwnerLens. Review before running.
# Requires the Microsoft Graph PowerShell SDK and an authenticated Graph session with Application.ReadWrite.All.
param(
  [string]$TagName = {{ tagName }}
)

$targets = @(
{{ targets }}
)

foreach ($target in $targets) {
  if ([string]::IsNullOrWhiteSpace($target.Owner)) {
    Write-Warning "Skipping $($target.ServicePrincipalId): no resolved owner."
    continue
  }

  $servicePrincipal = Get-MgServicePrincipal -ServicePrincipalId $target.ServicePrincipalId -Property Id,DisplayName,Tags -ErrorAction Stop
  $tagPrefix = "$TagName="
  $tags = @($servicePrincipal.Tags | Where-Object { -not $_.StartsWith($tagPrefix, [System.StringComparison]::OrdinalIgnoreCase) })
  $tags += "$TagName=$($target.Owner)"

  Update-MgServicePrincipal -ServicePrincipalId $target.ServicePrincipalId -Tags $tags -ErrorAction Stop
}
